# Generated by Django 3.2 on 2023-04-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Birth')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('adress', models.CharField(max_length=100, verbose_name='Adress')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('dni', models.CharField(max_length=100, verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=1000, verbose_name='Sub Title')),
                ('question', models.CharField(max_length=1000, verbose_name='Question')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('data', models.DateField(verbose_name='Date')),
                ('correct_answer', models.CharField(max_length=1000, verbose_name='Correct Answer')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coder.players', verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000, verbose_name='Answer')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coder.players', verbose_name='Player')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coder.questions', verbose_name='Question')),
            ],
        ),
    ]
