# Generated by Django 3.2 on 2023-04-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
