# Generated by Django 3.2 on 2023-04-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='dni',
        ),
    ]
