# Generated by Django 3.2 on 2023-04-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0002_questions_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='user',
        ),
    ]
