# Generated by Django 3.2 on 2023-04-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder', '0003_players_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='image',
            field=models.ImageField(default=1, upload_to='players'),
            preserve_default=False,
        ),
    ]
